### ISSUE TITLE
Webapps aren't working

### ISSUE THREAD

**Issue by laripappa** [att/XACML#31]
Hi everyone, 
I have cloned this repository and ran ```mvn clean install```
Build is complete, but ```mvn jetty:run-war``` isn't working well because I have not install jetty on local and pom.xml does't mention jetty either.
At first, modifying pom.xml below:
```
<plugin>
　<groupId>org.eclipse.jetty</groupId>
　<artifactId>jetty-maven-plugin</artifactId>
　<version>9.3.0.v20150612</version>
</plugin>
```

Then ```mvn jetty:run-war```, 
I got the messages below:
How to fix this error or should I make  a webapp based on jetty?
As I'm new to Java & maven, I really appreciate if you would solve my problem
```
[INFO] Scanning for projects...
[WARNING] The project com.att.research.xacml:att-xacml:pom:1.0.0 uses prerequisites which is only intended for maven-plugin projects but not for non maven-plugin projects. For such purposes you should use the maven-enforcer-plugin. See https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] ATT XACML
[INFO] att-xacml
[INFO] att-xacml-pdp
[INFO] xacml-test
[INFO] xacml-rest
[INFO] xacml-pdp-rest
[INFO] xacml-pap-rest
[INFO] xacml-pap-admin
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building ATT XACML 1.0.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> jetty-maven-plugin:9.3.0.v20150612:run-war (default-cli) > package @ att-xacml >>>
[INFO] 
[INFO] --- maven-source-plugin:2.2.1:jar-no-fork (attach-sources) @ att-xacml ---
[INFO] 
[INFO] --- maven-javadoc-plugin:2.9.1:jar (attach-javadocs) @ att-xacml ---
[INFO] Not executing Javadoc as the project is not a Java classpath-capable package
[INFO] 
[INFO] <<< jetty-maven-plugin:9.3.0.v20150612:run-war (default-cli) < package @ att-xacml <<<
[INFO] 
[INFO] 
[INFO] --- jetty-maven-plugin:9.3.0.v20150612:run-war (default-cli) @ att-xacml ---
[INFO] Configuring Jetty for project: ATT XACML
[INFO] Logging initialized @3222ms
[INFO] Context path = /
[INFO] Tmp directory = path/to/XACML/target/tmp
[INFO] Web defaults = org/eclipse/jetty/webapp/webdefault.xml
[INFO] Web overrides =  none
[INFO] jetty-9.3.0.v20150612
[WARNING] Web application not found /Users/AkiraFujiu/Lab/Program/xacml/att/XACML/target/att-xacml-1.0.0.war
[WARNING] Failed startup of context o.e.j.m.p.JettyWebAppContext@7c129ef6{/,null,null}{/Users/AkiraFujiu/Lab/Program/xacml/att/XACML/target/att-xacml-1.0.0.war}
java.io.FileNotFoundException: /Users/AkiraFujiu/Lab/Program/xacml/att/XACML/target/att-xacml-1.0.0.war
	at org.eclipse.jetty.webapp.WebInfConfiguration.unpack(WebInfConfiguration.java:495)
	at org.eclipse.jetty.maven.plugin.MavenWebInfConfiguration.unpack(MavenWebInfConfiguration.java:135)
	at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfiguration.java:72)
	at org.eclipse.jetty.maven.plugin.MavenWebInfConfiguration.preConfigure(MavenWebInfConfiguration.java:95)
	at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:475)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:511)
	at org.eclipse.jetty.maven.plugin.JettyWebAppContext.doStart(JettyWebAppContext.java:369)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:161)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:405)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:372)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.maven.plugin.AbstractJettyMojo.startJetty(AbstractJettyMojo.java:467)
	at org.eclipse.jetty.maven.plugin.AbstractJettyMojo.execute(AbstractJettyMojo.java:338)
	at org.eclipse.jetty.maven.plugin.JettyRunWarMojo.execute(JettyRunWarMojo.java:64)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] Started ServerConnector@3aff783c{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
[INFO] Started @3469ms
[INFO] Started Jetty Server
[INFO] Stopped ServerConnector@3aff783c{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
[INFO] Stopped o.e.j.m.p.JettyWebAppContext@7c129ef6{/,null,UNAVAILABLE}
{path/to/XACML/target/att-xacml-1.0.0.war}
[INFO] Jetty server exiting.
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building att-xacml 1.0.0
[INFO] ------------------------------------------------------------------------

```

**Comment by pdragosh** [comment]
You should run 'mvn jetty:run-war' in the directory of the webapp you want to run. Start with XACML-PAP-REST, then XACML-PDP-REST, and lastly XACML-PAP-ADMIN. Use 3 different terminal windows.

**Comment by laripappa** [comment]
Thank you! I got it.
