### ISSUE TITLE
Comments in begin of policy-file throws Exception

### ISSUE THREAD

**Issue by benkuly** [att/XACML#35]
All xml policy-files, that have a comment at the beginning throws an excpetion:

```
<?xml version="1.0" encoding="UTF-8"?>
 <!--This file was generated by the ALFA Plugin for Eclipse from Axiomatics AB (http://www.axiomatics.com). 
 Any modification to this file will be lost upon recompilation of the source ALFA file-->
<xacml3:PolicySet ...
```

```
com.att.research.xacml.std.dom.DOMStructureException: Exception loading Policy file "C:\...\src\main\resources\XACML\policy.xml": Exception parsing Policy: Unexpected element "null"
	at com.att.research.xacmlatt.pdp.policy.dom.DOMPolicyDef.load(DOMPolicyDef.java:125) ~[xacml-pdp-1.0.0.jar:na]
	at com.att.research.xacmlatt.pdp.std.StdPolicyFinderFactory.loadPolicyDef(StdPolicyFinderFactory.java:84) [xacml-pdp-1.0.0.jar:na]
	at com.att.research.xacmlatt.pdp.std.StdPolicyFinderFactory.getPolicyDefs(StdPolicyFinderFactory.java:148) [xacml-pdp-1.0.0.jar:na]
	at com.att.research.xacmlatt.pdp.std.StdPolicyFinderFactory.init(StdPolicyFinderFactory.java:195) [xacml-pdp-1.0.0.jar:na]
	at com.att.research.xacmlatt.pdp.std.StdPolicyFinderFactory.getPolicyFinder(StdPolicyFinderFactory.java:221) [xacml-pdp-1.0.0.jar:na]
	at com.att.research.xacmlatt.pdp.std.StdEvaluationContextFactory.getPolicyFinder(StdEvaluationContextFactory.java:78) [xacml-pdp-1.0.0.jar:na]
	at com.att.research.xacmlatt.pdp.std.StdEvaluationContextFactory.getEvaluationContext(StdEvaluationContextFactory.java:149) [xacml-pdp-1.0.0.jar:na]
	at com.att.research.xacmlatt.pdp.ATTPDPEngine.decide(ATTPDPEngine.java:188) [xacml-pdp-1.0.0.jar:na]

Caused by: com.att.research.xacml.std.dom.DOMStructureException: Exception parsing Policy: Unexpected element "null"
	at com.att.research.xacmlatt.pdp.policy.dom.DOMPolicyDef.newInstance(DOMPolicyDef.java:64) ~[xacml-pdp-1.0.0.jar:na]
	at com.att.research.xacmlatt.pdp.policy.dom.DOMPolicyDef.load(DOMPolicyDef.java:123) ~[xacml-pdp-1.0.0.jar:na]

Caused by: com.att.research.xacml.std.dom.DOMStructureException: Unexpected element "null"
	at com.att.research.xacml.std.dom.DOMUtil.newUnexpectedElementException(DOMUtil.java:151) ~[xacml-1.0.0.jar:na]
	at com.att.research.xacmlatt.pdp.policy.dom.DOMPolicyDef.newInstance(DOMPolicyDef.java:61) ~[xacml-pdp-1.0.0.jar:na]



```

**Comment by pdragosh** [comment]
Hi, thanks I will take a look at this. How are you testing this in order to generate the error?

**Comment by benkuly** [comment]
```
properties props = new Properties();
props.setProperty(XACMLProperties.PROP_ROOTPOLICIES, "policy");
props.setProperty("policy.file", "src/main/resources/XACML/policy.xml");
PDPEngine engine = PDPEngineFactory.newInstance().newEngine(props);

Request request = //simple XAML request
Response response = engine.decide(request);
```
If I remove the comment from policy file the request will be responed without error.

**Comment by g-spot** [comment]
Hi, any news on this? I am facing exactly the same problem.

**Comment by alexkcoder** [comment]
I've seen this issue as well. I have submitted the following pull request https://github.com/att/XACML/pull/38

**Comment by ygrignon-sfdc** [comment]
@benkuly @g-spot should be fixed now
